// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfdjzxpxnjvcamhbpiwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZGp6eHB4bmp2Y2FtaGJwaXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjY2MjksImV4cCI6MjA1ODMwMjYyOX0.0TwZbJBBHe5t8zwa5Dok37t0VHpssEty6NPJOiNkF7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);